apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: bryanl/websay
  newName: bryanl/websay
  newTag: a61c7c9b1cfcd53e3e5565e9a2f91f62c15678bb
